name: Benchmark Bun.js vs Node.js (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up permissions for setupandrun.sh
      run: chmod +x setup-and-run.sh
      shell: bash

    - name: Run setupandrun.sh
      shell: bash
      run: ./setup-and-run.sh

    - name: Upload results.txt as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: result-file
        path: results.txt

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-report
        path: report.html
